### ISSUE TITLE
Clarification: Fails with error 4 with RH Eval subscription

### ISSUE THREAD

**Issue by raghur** [haroldwongms/openshift-containerplatform#13]
Hi,

I'm trying to use your ARM template with Azure with a RH openshift container platform 30 day eval license (says 2 core). I'm running into error 4 on the custom script.

Does this mean that this template cannot be used with the RH eval subscription since the entitlements are too low?

PS - I'm using DS2_v1 images (added those to the image sizes)

**Comment by mglantz** [comment]
I'm verifying this, but one 2 core subscription should equal 4 vCPUs in Azure. How many in total do you consume?

**Comment by mglantz** [comment]
You can login to access.redhat.com and validate total number of subscriptions as well. Doesn't matter that it is an eval, but I would guess you are using more than you have. Either way, you are best off with creating a support ticket /w Red Hat as this has nothing to do with the OCP templates here.

**Comment by haroldwongms** [comment]
My template deploys a minimum of 5 VMs today.  One is the Bastion node which is not required after cluster spin up but does consume one of the licenses just for RHEL which is also part of the OpenShift license.  The Load Balancer (HA Proxy) also consumes a license.  Then you have at least 1 master, 1 infra and 1 node.

I would go with what Magnus suggested - contact Red Hat and see if you can get an increase in evaluation licenses.

**Comment by mglantz** [comment]
It's only the app nodes which consumes OpenShift subscriptions, everything else is included in those.

**Comment by raghur** [comment]
I'm going to close this since it's got more to do with RH entitlements than anything else. Thanks for the info.
