### ISSUE TITLE
change to docker version to 1.12.6.x for 3.5 release 

### ISSUE THREAD

**Issue by ivanthelad** [haroldwongms/openshift-containerplatform#20]
The current 3.5 release documentation states that  docker 1.12.6 is the tested docker version that should be installed. The scripts explicity install 1.12.5
https://github.com/haroldwongms/openshift-containerplatform/blob/master/scripts/nodePrep.sh#L67

This should be changed to 1.12.6

https://access.redhat.com/articles/2176281

**Comment by haroldwongms** [comment]
Thank you.  Will include this change in my final updates.
