### ISSUE TITLE
update azuredeploy.parameters.json line 83 and 86 

### ISSUE THREAD

**Issue by dwojciec** [haroldwongms/openshift-containerplatform#21]
the 2 lines has to be changed (remove the 27 and 28)
https://github.com/haroldwongms/openshift-containerplatform/blob/master/azuredeploy.parameters.json#L83
and
https://github.com/haroldwongms/openshift-containerplatform/blob/master/azuredeploy.parameters.json#L86

The deployment failed with this error:
Deployment template validation failed: 'The template parameters '27.aadClientId, 28.aadClientSecret' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time.

**Comment by haroldwongms** [comment]
Thank you.  Changes made.
