### ISSUE TITLE
Deploy Template cli 2.0 : --no-wait and not --nowait

### ISSUE THREAD

**Issue by dwojciec** [haroldwongms/openshift-containerplatform#22]
In the README.md file in the Deploy Template section (https://github.com/haroldwongms/openshift-containerplatform#deploy-template)
the right command for azure cli 2.0 is 

az group deployment create --name <deployment name> --template-file <template_file> --parameters @<parameters_file> --resource-group <resource group name> --no-wait

exemple:
az group deployment create --name ocpdeployment --template-file azuredeploy.json --parameters @azuredeploy.parameters.json --resource-group ocpazure35 --no-wait

**Comment by haroldwongms** [comment]
Thank you.  Changes made.
