### ISSUE TITLE
At the end of deployement the infra and apps nodes are deleted just after the cloudprovider stuff

### ISSUE THREAD

**Issue by dwojciec** [haroldwongms/openshift-containerplatform#23]
I wanted to deploy 3 nodes (1 master, 1 apps node and 1 infra node) but at the end I'm able to access the master but the 2 nodes (infra and apps node) are not part of the cluster.

I checked on the bastion the /var/lib/waagent/custom-script/download/1
and I saw in the stdout file associated to de deployOpenshift.sh this 2 command 

PLAY RECAP *********************************************************************
dwojciec-infra-0           : ok=4    changed=3    unreachable=0    failed=0
dwojciec-master-0          : ok=5    changed=4    unreachable=0    failed=0
dwojciec-node-0            : ok=4    changed=3    unreachable=0    failed=0

Thu Apr 27 07:58:17 UTC 2017 - Delete stuck nodes

PLAY [nfs] *********************************************************************

TASK [Delete stuck nodes] ******************************************************
changed: [dwojciec-master-0] => (item=oc delete node dwojciec-infra-0)
changed: [dwojciec-master-0] => (item=oc delete node dwojciec-node-0)

PLAY RECAP *********************************************************************
dwojciec-master-0          : ok=1    changed=1    unreachable=0    failed=0

Why the 2 apps and infra nodes are deleted after the setup of the cloudprovider stuff ?

I have just restarted ansible from the bastion manually using 
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
and now I have 
oc get nodes
NAME                STATUS                     AGE
dwojciec-infra-0    Ready                      14m
dwojciec-master-0   Ready,SchedulingDisabled   1h
dwojciec-node-0     Ready                      14m

Note: it will be vey useful to have an additional parameter inside the template to be able to provision only the infrastructure and not to deploy OCP. For example if we want to test new OCP version (example 3.5) not part of the full deployment and to run it manually.

**Comment by haroldwongms** [comment]
The process in which I am configuring Azure Cloud Provider for integration with Azure causes the Infra and App Node to get "stuck".  If you wait a few minutes, these two nodes will be in a state of "NotReady".  For some reason, when configuring the Azure Cloud Provider settings, there is an issue with OpenShift configuring the nodes successfully.  Upon deleting the nodes, the new configuration will take effect and these nodes should be added back into the cluster.  I have tested that deployment many times so not sure why it is not working for you.

**Comment by haroldwongms** [comment]
Please refer to http://aka.ms/openshift for links to current templates.  

Closing this issue.
