### ISSUE TITLE
Metrics, logging and persistent storage

### ISSUE THREAD

**Issue by mglantz** [haroldwongms/openshift-containerplatform#6]
Hey there,

What do you think about adding metrics, logging and persistent storage via NFS (put on a master server)? I've gotten that to work in a downstream repo of mine, based on the old openshift-enterprise repo.

**Comment by mglantz** [comment]
I've worked my patches into a fork of this repo instead. Doing testing now.

**Comment by haroldwongms** [comment]
Boy, you've been busy today.  :-)

I had considered including the NFS piece about 2 weeks ago as well, but decided not to include for now.  I was thinking of adding an option to include it.  I also was going to do a variable to enable cockpit so it doesn't have to be on if you don't want it.  Thanks for all the feedback items.  Perhaps you can look into enabling these capabilities as an optional item in your fork?

**Comment by mglantz** [comment]
I think cockpit is something you always need, as without it, you have no GUI means to check on 1) cluster health 2) node utilization 3) what images are running in which projects (key to doing LCM). 4) registry 5) project visualisation, where you get a graphical representation of pods, nodes, replications controllers, etc - a feature that moved from OpenShift to Cockpit in OCP 3.2 -> 3.3+

How I reasoned with myself regarding the storage: If we do not setup any persistent storage, the cluster cannot be used to do anything except for to demo features, as nothing gets saved. Based on that, I think NFS is better than anything at this point. 

When we get Azure cloud storage integration (it's being worked on, doesn't work today... even though I know it's already in the manuals) that should be what we use instead, as it will be better performance and be able to provide storage and persistent volumes automatically and on-demand.

In the long run, there can be options perhaps to selection between Azure cloud storage or NFS, Gluster or Ceph. 

I'm still testing, I didn't see that some stuff like artifacts where hardcoded to point to this repo. Should have something working today though.

**Comment by mglantz** [comment]
From initial testing, a single cluster comes up OK. A multi-master cluster with two nodes does not get setup OK. Troubleshooting.

**Comment by mglantz** [comment]
A single cluster is all OK. Metrics work, logging works, persistent storage worksa and deployment of apps (also checked that data is written to PV).

Looking at why the HA cluster does not get setup properly. The cluster does come up, but metrics and logging does not get setup. Theory is that it's related to the persistent storage.

**Comment by mglantz** [comment]
I think it's fixed now, will do testing later :-)

**Comment by haroldwongms** [comment]
When you get it working, please issue the PR and I'll merge.

Also, can we start a regular email thread?  My email is Harold.wong@microsoft.com.  Thanks.

Harold
